#!/usr/bin/zsh
for i in *(.); do
	echo "-----------\n$i\n-----------";
	while IFS= read -r line; do
    	echo "$line"
	done < $i;
	for ii in {1..3}; do
		for i in {1..$COLUMNS}; do
			echo -n "=";
		done
		echo;
	done
done

