bind -n M-H select-pane -L
bind -n M-L select-pane -R
bind -n M-K select-pane -U
bind -n M-J select-pane -D

#unbind C-b
set-option -g prefix M-e 
bind-key M-e send-prefix

set -g default-terminal "xterm-256color"
set -as terminal-features ",xterm-256color:RGB"

#setw -g mode-style 'fg=#dc143C bg=#dc143C bold'
set -g pane-active-border-style 'fg=grey'
set -g status-style 'fg=#dc143C'
set -g status-right-style 'fg=#dc143C'
setw -g window-status-current-style 'fg=#dc143C bold'

set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides "tmux-256color:Tc"


set -g mouse off
set -g default-command $SHELL
set-option -g base-index 1
set-option -g allow-rename off

# new windows inherit current pane's path
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind r source-file ~/.tmux.conf

bind x kill-pane
bind v new

bind k if-shell '[ "#{session_name}" != "D" ]' \
    'run-shell "tmux switch-client -p && tmux kill-session -t #{session_name}"' \
    'display-message "Cannot kill session D"'
