set -g mouse off
set -g default-command $SHELL
set-option -g base-index 1
set-option -g allow-rename off

# new windows inherit current pane's path
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

bind x kill-pane
bind v new

bind k if-shell '[ "#{session_name}" != "D" ]' \
    'run-shell "tmux switch-client -p && tmux kill-session -t #{session_name}"' \
    'display-message "Cannot kill session D"'
