#!/bin/sh

CopyFiles() {
    (
        cd $rootDirPath
        for i in $(tree -if *); do
            if [[ -f $i ]]; then
                echo "sudo cat $rootDirPath/$i > /$i"
                sudo cat $rootDirPath/$i > /$i
            fi
        done
        unset i
    )
    
}

Backup() {
    (
        cd $rootDirPath
        for i in $(tree -if *); do
            if [[ -f $i ]]; then
                echo "sudo cat /$i > $rootDirPath/$i"
                #sudo cat $rootDirPath/$i > /$i
            fi
        done
        unset i
    )
}

case $(uname -m) in 
aarch64)
    rootDirPath=$(dirname $0)/root-aarch64
    ;;
x86_64)
    rootDirPath=$(dirname $0)/root-x86_64
    ;;
esac

if [ "$(id -u)" -ne 0 ]; then
    echo "you must be root"
else
#    echo "back" && Backup
    echo "copy" && CopyFiles
#    BlackArchSetup
    unset rootDirPath
fi

