#!/usr/bin/zsh

Main() {
    local FileSystemPath=$myFSPath;
    local mountpoint;
    local usbname;
    
    if [[ ! $myDevicePath ]]; then
        echo "ERROR \$myDevicePath NOT FOUND";
        return;
    fi

    if [[ $FileSystemPath ]]; then
        mountpoint=$FileSystemPath;
    else
        mountpoint=/fs;
    fi

    if [[ ! -d $mountpoint ]]; then
        sudo mkdir $mountpoint;
    fi   

    local list_dev=$(lsblk -n -o NAME,SIZE,MOUNTPOINTS --include 8,259);
    if [[ $list_dev ]]; then
        echo "$list_dev";
    else
        echo "ERROR ANY DEV NOT FOUND";
        return;
    fi

    echo -n "$myDevicePath/";
    read usbname;

    if [[ $usbname == "" ]]; then
        return;
#    elif [[ $usbname == ?"?"* ]]; then
#        case $usbname in
#        "n?");;
#        "i?");;
#        esac
    elif [[ ! -e "$myDevicePath/$usbname" ]]; then
        echo "ERROR DEV NOT FOUND";
        return;
    else
        if [[ ! -d $mountpoint/$usbname ]]; then
            sudo mkdir $mountpoint/$usbname;
        fi   

        if [[ $(findmnt --source "$myDevicePath/$usbname") ]]; then
            #UMOUNTING
            if [[ $PWD == $mountpoint/* ]]; then
                cd $mountpoint;
            fi

            echo "Umounting...";
            
            sudo umount $myDevicePath/$usbname;
            if [[ ! $(findmnt --target "$mountpoint/$usbname") ]]; then
                mv -v $mountpoint/$usbname /tmp;
            fi

            echo "Done";
        elif [[ ! $(findmnt --source "$myDevicePath/$usbname") ]]; then
            #MOUNTING
            sudo mount $myDevicePath/$usbname $mountpoint/$usbname;
            
            if [[ $(findmnt --source "$myDevicePath/$usbname") ]]; then
                echo "Mounting...";
                echo ">>> $mountpoint/$usbname <<<";
            fi
        fi
    fi
}

sudo -v || return 1;
Main;
