[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0:file:///home/ncor/data/Media/Images/P.nobk/a/meh/Xeno1.png)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x3\xc6\0\0\0\x1\0\0\a~\0\0\x2\x15\0\0\x3\xc6\0\0\0\x1\0\0\a~\0\0\x2\x15\0\0\0\0\0\0\0\0\a\x80\0\0\x3\xc6\0\0\0\x1\0\0\a~\0\0\x2\x15)

[FullScreen]
pos=@Point(560 1016)
screen=@Rect(0 0 1920 1080)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(953 462)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[OpenDialog]
advanced=false
netMRL=
size=@Size(526 400)

[Preferences]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x2\x30\0\0\0\xbe\0\0\x5O\0\0\x3y\0\0\x2\x30\0\0\0\xbe\0\0\x5O\0\0\x3y\0\0\0\0\0\0\0\0\a\x80\0\0\x2\x30\0\0\0\xbe\0\0\x5O\0\0\x3y)

[RecentsMRL]
list=file:///home/ncor/Downloads/6b4457c13575aa58b6f4990c6c88baf8.mp4, file:///home/ncor/data/Media/Images/P.nobk/a/meh/Xeno_original.png, file:///home/ncor/data/Media/Images/P.nobk/a/meh/Xeno1_original.png, file:///home/ncor/data/Media/Images/P.nobk/a/meh/Xeno1.png, file:///home/ncor/data/Media/Images/P.nobk/a/meh/Xeno.png, file:///home/ncor/data/Media/Images/P.nobk/a/meh/Roxy_original.png, file:///home/ncor/data/Media/Images/P.nobk/a/meh/Roxy1_original.png, file:///home/ncor/data/Media/Images/P.nobk/a/meh/Roxy1.png, file:///home/ncor/data/Media/Images/P.nobk/a/meh/Roxy.png, file:///home/ncor/data/Media/Images/P.nobk/a/meh/Loba.png, file:///home/ncor/data/Media/Images/P.nobk/a/meh/Dva_nude_original.png, file:///home/ncor/data/Media/Images/P.nobk/a/meh/Dva_nude.png, file:///home/ncor/data/Media/Images/P.nobk/a/meh/Dva_clothes_original.png, file:///home/ncor/data/Media/Images/P.nobk/a/meh/Dva_clothes.png, directory:///home/ncor/data/Media/Images/P.nobk/a/meh, file:///home/ncor/.local/share/Trash/files/6b4457c13575aa58b6f4990c6c88baf8.mp4.2, file:///home/ncor/.local/share/Trash/files/6b4457c13575aa58b6f4990c6c88baf8.mp4, file:///home/ncor/data/Media/Images/P.nobk/a/HHHp1.zip, file:///home/ncor/data/01/py/mvpy/outputs/thumbnails_per_frame/4/samus1.mp4, file:///home/ncor/data/01/py/mvpy/outputs/thumbnails_per_frame/3/samus2.mp4, file:///home/ncor/data/01/py/mvpy/inputs/samus1.mp4, file:///home/ncor/data/01/py/mvpy/inputs/samus2.mp4
times=46700, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 80233, 11400, 0, 927100, 134550, 0, 0

[VLM]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x3\xc6\0\0\0\x1\0\0\a~\0\0\x2\x15\0\0\x3\xc6\0\0\0\x1\0\0\a~\0\0\x2\x15\0\0\0\0\0\0\0\0\a\x80\0\0\x3\xc6\0\0\0\x1\0\0\a~\0\0\x2\x15)
