[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\n/home/ncor)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x3\xc6\0\0\0\x1\0\0\a~\0\0\x4\x36\0\0\x3\xc6\0\0\0\x1\0\0\a~\0\0\x4\x36\0\0\0\0\0\0\0\0\a\x80\0\0\x3\xc6\0\0\0\x1\0\0\a~\0\0\x4\x36)

[FullScreen]
pos=@Point(0 0)
screen=@Rect(0 0 0 0)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(953 1007)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[RecentsMRL]
list=file:///home/ncor/Downloads/6b4457c13575aa58b6f4990c6c88baf8.mp4, file:///home/ncor/data/01/py/mvpy/outputs/thumbnails_per_frame/4/samus1.mp4, file:///home/ncor/data/01/py/mvpy/outputs/thumbnails_per_frame/3/samus2.mp4, file:///home/ncor/data/01/py/mvpy/inputs/samus1.mp4, file:///home/ncor/data/01/py/mvpy/inputs/samus2.mp4
times=0, 927100, 134550, 0, 0
