#!/bin/sh

defaultApps=(
    inotify-tools
    less
    zsh
    git
    tmux
    fastfetch
    tree
    rsync
    neovim
    man-db
    htop
    xplr
    viu
)

ArchArmSetup() {

}

ArchSetup() {
    pcAppsSpecific=(
        steam
        discord
    )

    arr2=(
        hyprlock
        wl-clipboard
    #TUI image viewer
        viu
    #TUI file mannagers
        xplr
    #WindowManager
        hyprland
    #Panel
        waybar
    #GUI file mannagers
        dolphin
    )
}

BlackArchSetup() {
    curl -O https://blackarch.org/strap.sh && chmod +x strap.sh
    echo "Now only find and delete something like -> pacman -S --noconfirm --needed blackarch-officials"
    echo "Then sudo ./strap.sh"
}

PostSetup() {
    sudo cp -r pacman.conf /etc/pacman.conf
    sudo cp -r os-release /etc/os-release
    chsh -s /usr/bin/zsh
}

case $(uname -m) in
    #"x86_64") ArchSetup ;;
    #"aarch64") ArchArmSetup ;;
    *) echo "$(uname -m) is not in case" ;;
esac

sudo pacman -Syu 
sudo pacman -S --needed ${defaultApps[@]} ${arr1[@]}

#BlackArchSetup
#PostSetup
