#!/usr/bin/bash


BlackArchSetup() {
    curl -O https://blackarch.org/strap.sh && chmod +x strap.sh
    echo "Now only find and delete something like -> pacman -S --noconfirm --needed blackarch-officials"
    echo "Then sudo ./strap.sh"
}
ArchArmSetup() {
    arr1=(
        inotify-tools
        less
        zsh
        git
        tmux
        fastfetch
        tree
        rsync
        neovim
        man-db
    )
    sudo pacman -Syu ${arr1[@]}
    unset arr1
}

ArchSetup() {
    arr1=(
        steam
        discord
    )

    arr2=(
        inotify-tools
        less
        zsh
        git
        tmux
        fastfetch
        tree
        rsync
        swaybg
        neovim
        man-db
        hyprlock
        wl-clipboard
    #TUI image viewer
        viu

    #TUI file mannagers
        xplr

    #WindowManager
        hyprland

    #Panel
        waybar

    #GUI file mannagers
        dolphin
    )
    sudo pacman -Syu ${arr[@]}
    unset arr1
    unset arr2
}

PostSetup() {
    sudo cp -r pacman.conf /etc/pacman.conf
    sudo cp -r os-release /etc/os-release
    chsh -s /usr/bin/zsh
}

#ArchSetup
ArchArmSetup
#BlackArchSetup
#PostSetup
