#!/bin/sh

archOpt=(
    "x86_64"
    "aarch64"
)

defaultApps=(
    inotify-tools
    less
    zsh
    git
    tmux
    fastfetch
    tree
    rsync
    neovim
    man-db
    htop
    xplr
    viu
)

ArchSetup() {
    case $arch in
    ${archOpt[0]})
        archAppsSpecific=(
            steam
            discord

            hyprlock
            wl-clipboard
            #WindowManager
            hyprland
            #GUI file mannagers
            #dolphin
        )
        ;;
    ${archOpt[1]})
        archAppsSpecific=()
        ;;
    *)
        echo "architecture unknown"
        ;;
    esac
}

BlackArchSetup() {
    curl -O https://blackarch.org/strap.sh && chmod +x strap.sh
    echo "Now only find and delete something like -> pacman -S --noconfirm --needed blackarch-officials"
    echo "Then sudo ./strap.sh"
}

PostSetup() {
    sudo cp -r pacman.conf /etc/pacman.conf
    sudo cp -r os-release /etc/os-release
    #chsh -s /bin/zsh
}

arch=$(uname -m)
sudo pacman -Syu 
sudo pacman -S --needed ${defaultApps[@]}

ArchSetup
#BlackArchSetup
#PostSetup
sudo pacman -Syu --needed ${archAppsSpecific[@]}

unset archAppsSpecific
unset defaultApps
unset arch
unset archOpt
