#!/bin/sh

BlackArchSetup() {
    curl -O https://blackarch.org/strap.sh && chmod +x strap.sh
    echo "Now only find and delete something like -> pacman -S --noconfirm --needed blackarch-officials"
    echo "Then run sudo ./strap.sh"
}

CopyFiles() {
    (
        cd $rootDirPath
        for i in $(tree -if *); do
            if [[ -f $i ]]; then
                echo "sudo cat $rootDirPath/$i > /$i"
                #sudo cat $rootDirPath/$i > /$i
            fi
        done
        unset i
    )
    
}

case $(uname -m) in 
aarch64)
    rootDirPath=$(dirname $0)/root-aarch64
    ;;
x86_64)
    rootDirPath=$(dirname $0)/root-x86_64
    ;;
esac

if [ "$(id -u)" -ne 0 ]; then
    echo "you must be root"
else
    CopyFiles
#    BlackArchSetup
    unset rootDirPath
fi

