#!/bin/sh

BlackArchSetup() {
    curl -O https://blackarch.org/strap.sh && chmod +x strap.sh
    echo "Now only find and delete something like -> pacman -S --noconfirm --needed blackarch-officials"
    echo "Then sudo ./strap.sh"
}

PostSetup() {
    (
        cd $rootDirPath
        for i in $(tree -if *); do
            if [[ -f $i ]]; then
                echo "sudo cp -r $i /$i"
                echo "mv $i $(dirname $0)/tmp"
                echo "ln /$i $i"
                echo ""
            fi
        done
        unset i
    )
}

case $(uname -m) in 
aarch64)
    rootDirPath=$(dirname $0)/root-aarch64
    ;;
x86_64)
    rootDirPath=$(dirname $0)/root-x86_64
    ;;
esac

if [ "$(id -u)" -ne 0 ]; then
    echo "you must be root"
else
#    BlackArchSetup
    PostSetup
    unset rootDirPath
fi

