#!/bin/zsh

Main() {
    git pull

    while true; do
        echo -n "[1] Commit\n[2] Upload\n[x] exit\n>>> "
        read var
        case $var in
        "1")
            echo "a"
            ;;
        "2")
            echo "b"
            ;;
        "x") return ;;
        esac
    done

    unset var
    return 0;
}
Main;
