#!/usr/bin/zsh

Start() {
	if [[ $(sudo vncserver :1 -localhost no) ]]; then
		echo "KEX STARTED";
	fi
}

Stop() {
	if [[ $(sudo vncserver -kill -clean :1) ]]; then
		echo "KEX STOPPED";
	fi
}

List() {sudo vncserver -list -cleanstale :1}

Main() {
	case $1 in
		"s")Start;;
		"x")Stop;;
		"l")List;;
		"")echo "ERROR ARGS NOT PASSED";;
		*)echo "ERROR ARGS ARE INCORECT";;
	esac
}
sudo -v || return 1;
Main $1;
