#!/bin/zsh

Main() {
    (
        cd ~
        
        while true; do
            if ping -c1 -W1 8.8.8.8 &>/dev/null; then
                #ONLINE
                git pull
            else
                while true; do
                    if ping -c1 -W1 8.8.8.8 &>/dev/null; then
                        #ONLINE
                        git pull &>/dev/null
                        (date > $HOME/log.txt)
                        break
                    fi
                    sleep 60
                done &
            fi

            print -n "[0] Fetch\n[1] Status\n[2] Commit\n[3] Upload\n[c] Clear\n[x] exit\n>>> "
            read UserInput
            chars=(${(s::)UserInput})

            for i in $chars[@]; do
                case $i in
                    "0") git pull;;
                    "1") git status;;
                    "2") git add . && git commit -m "$(TZ="Europe/Prague" date +"%d.%m.%Y-%Hh%Mm%Ss")";;
                    "3") git push;;
                    "c") clear;;
                    "x") return;;
                esac
            done
        done

        unset UserInput
    )
}
Main $1
