#!/bin/zsh

Foo() {
    for i in $@; do
        case $i in
            "0") git pull;;
            "1") git status;;
            "2") git add . && git commit -m "$(TZ="Europe/Prague" date +"%d.%m.%Y-%Hh%Mm%Ss")";;
            "3") git push;;
            "c") clear;;
            "x") unset i; exit;; 
        esac
    done
    unset i

}

Main() {
    #
    if [[ ! ${#@} -eq 0 ]]; then 
        chars=(${(s::)1})
        Foo $chars
        return;
    fi
    
    (
        cd ~
        git pull
              
        while true; do
            print -n "[0] Fetch\n[1] Status\n[2] Commit\n[3] Upload\n[c] Clear\n[x] exit\n>>> "
            read UserInput
            chars=(${(s::)UserInput})

            Foo $chars
        done

        unset UserInput
        unset chars
    )
}
Main $1
