#!/usr/bin/zsh

if [[ -d /home/chromagor/.local/share/Steam/steamapps/compatdata/306130/pfx/drive_c/users/steamuser/'My Documents'/'Elder Scrolls Online'/live/AddOns/TamrielTradeCentre ]]; then
	(
		cd /home/chromagor/.local/share/Steam/steamapps/compatdata/306130/pfx/drive_c/users/steamuser/'My Documents'/'Elder Scrolls Online'/live/AddOns/TamrielTradeCentre
		curl https://eu.tamrieltradecentre.com/download/PriceTable > PriceTable.zip
		unzip PriceTable.zip
	)
fi
