#!/usr/bin/zsh

Main() {
    local devPath=$myDevicePath;
    local mountpoint;


    if [[ $myFSPath ]]; then
        mountpoint=$myFSPath;
    else
        mountpoint=/fs;
    fi


    if [[ ! -d $mountpoint ]]; then
        mkdir $mountpoint;
    fi   


    local list_dev=$(lsblk -n -o NAME,SIZE,MOUNTPOINTS --include 8,259);
    if [[ $list_dev ]]; then
        echo "$list_dev";
    else
        echo "ERROR ANY DEV NOT FOUND";
        return;
    fi


    echo -n "$devPath/";
    local usbname;
    read usbname;
    if [[ $usbname == "" ]]; then
        return;
    elif [[ $usbname == *"?"* ]]; then
        #n? --> custom usbname
        #i? --> more info
        #... --> ...
        echo "\ncommand: $usbname\ncommand lenght: ${#usbname}";
    elif [[ ! -e "$devPath/$usbname" ]]; then
        echo "ERROR DEV NOT FOUND";
        return;
    else
        if [[ ! -d $mountpoint/$usbname ]]; then
            mkdir $mountpoint/$usbname;
        fi   


        if [[ $(findmnt --source "$devPath/$usbname") ]]; then
            #UMOUNTING
            if [[ $PWD == $mountpoint/* ]]; then
                cd $mountpoint;
            fi


            echo "Umounting...";
            sudo umount $devPath/$usbname;
            echo "Done";
        elif [[ ! $(findmnt --source "$devPath/$usbname") ]]; then
            #MOUNTING
            sudo mount $devPath/$usbname $mountpoint/$usbname;
            if [[ $(findmnt --source "$devPath/$usbname") ]]; then
                echo "Mounting...";
                echo ">>> $mountpoint/$usbname <<<";
            fi
        fi
    fi
}

sudo -v || return 1;
Main;
